rootProject.name = "public"

include(":Anonymizer")
include(":AutoClicker")
include(":AutoPrayFlick")
include(":BossSwapper")
include(":CustomSwapper")
include(":ExtUtils")
include(":ItemDropper")
include(":LeftClickCast")
include(":NeverLog")
include(":OneClick")
include(":Shayzien")
include(":alchemicalhydra")
include(":aoewarnings")
include(":betterequipmentinspector")
include(":castlewarsextended")
include(":cerberus")
include(":clanmanmode")
include(":coxhelper")
include(":dagannothkings")
include(":demonicgorilla")
include(":dropparty")
include(":dynamicmaxhit")
include(":effecttimers")
include(":entityfocuspile")
include(":entityhiderextended")
include(":environmentaid")
include(":fightcave")
include(":fightcavespawnrotation")
include(":gauntletextended")
include(":godbook")
include(":grotesqueguardians")
include(":hallowedsepulchre")
include(":hideprayers")
include(":hideunder")
include(":hotkeytowalk")
include(":hydra")
include(":inferno")
include(":kalphitequeen")
include(":leftclickblackjack")
include(":lizardmenshaman")
include(":lootassist")
include(":menuentryswapperextended")
include(":multiindicators")
include(":nex")
include(":nightmare")
include(":npcstatus")
include(":npcindicatorsextended")
include(":pileindicators")
include(":playerattacktimer")
include(":playerscouter")
include(":prayagainstplayer")
include(":pvptools")
include(":reorderprayers")
include(":smithing")
include(":socket")
include(":socketchat")
include(":socketdeathindicator")
include(":socketplayerstatus")
include(":socketplayerstatusextended")
include(":socketsotetseg")
include(":socketspecialcounter")
include(":sorceressgarden")
include(":spawntimer")
include(":specbar")
include(":specorb")
include(":spellbook")
include(":strongholdofsecurity")
include(":tarnslair")
include(":templetrekking")
include(":theatre")
include(":ticktimers")
include(":vetion")
include(":vorkath")
include(":wildernesslocations")
include(":zulrah")

for (project in rootProject.children) {
    project.apply {
        projectDir = file(name)
        buildFileName = "${name.toLowerCase()}.gradle.kts"

        require(projectDir.isDirectory) { "Project '${project.path} must have a $projectDir directory" }
        require(buildFile.isFile) { "Project '${project.path} must have a $buildFile build script" }
    }
}
