name: Plugins - CI (Push)

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build

    steps:
      - name: Checkout Plugins
        uses: actions/checkout@v3

      - name: Checkout Client
        uses: actions/checkout@v3
        with:
          repository: open-osrs/runelite
          ref: master
          path: open-osrs
      
      - name:Checkout Client Plugins
        uses: actions/checkout@v3
        with:
          repository: open-osrs/plugins
          ref: master
          path: plugins

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 11
          cache: 'gradle'

      - name: Assembling client
        run: ./gradlew assemble --console=plain
        working-directory: open-osrs

      - name: Building client
        run: ./gradlew build -x test -x checkstyleMain --console=plain
        working-directory: open-osrs

      - name: Upload client artifacts to local maven
        run: ./gradlew publishToMavenLocal --console=plain
        working-directory: open-osrs
      
      - name: Make gradlew executable (Client Plugins)
        run: chmod +x ./gradlew
        working-directory: plugins

      - name: Assembling Client plugins
        run: ./gradlew --console=plain
        working-directory: plugins

      - name: Building Client plugins
        run: ./gradlew -x test -x checkstyleMain --console=plain
        working-directory: plugins

      - name: Upload Client plugins artifacts to local maven
        run: ./gradlew --console=plain
        working-directory: plugins

      - name: Make gradlew executable (plugins)
        run: chmod +x ./gradlew

      - name: Assembling plugins
        run: ./gradlew assemble --console=plain

      - name: Building plugins
        run: ./gradlew build
